<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ThreadPoolMaxThreads>20</ThreadPoolMaxThreads>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Logs\**" />
	  <Compile Remove="Properties\PublishProfiles\**" />
	  <Content Remove="Logs\**" />
	  <Content Remove="Properties\PublishProfiles\**" />
	  <EmbeddedResource Remove="Logs\**" />
	  <EmbeddedResource Remove="Properties\PublishProfiles\**" />
	  <None Remove="Logs\**" />
	  <None Remove="Properties\PublishProfiles\**" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\setup\client.tmp" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Logs\readme.txt" />
	</ItemGroup>

	<ItemGroup>  
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />  
		<PackageReference Include="Npgsql" Version="8.0.8" />  
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" /> 
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
		<PackageReference Include="UzEx.Storage.MinIO" Version="3.0.0" />
		<PackageReference Include="X.PagedList" Version="8.0.7" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.1" />
		<PackageReference Include="AspNetCore.HealthChecks.MySql" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\EX.Data\EX.Data.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Protobuf Include="..\..\protos\account.proto" GrpcServices="Server" Link="Protos\account.proto" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="appsettings.Development.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="wwwroot\records\readme.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\setup\client.msi">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\setup\release.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\setup\setup.exe">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\setup\updater.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\tmp\uzex">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <None Update="start.bat">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
